# Config for baseline WaveRNN.
data:
  clip_frames: 3
  padding_frames: 6
  batch_size: 64
  mel:
    sample_rate: 22050
    n_fft: 1024
    n_mels: 80
    fmin: 0.0
    fmax: 11025.0
    hop_length: 256
    win_length: 512
    log_epsilon: 1.0e-3
    pre_emphasis: 0.0

conditioner:
  layers: 3
  channels: 256
  width: 5

autoregressive:
  gru_dimension: 1024
  hidden_dimension: 1024

prune:
  final_sparsity: 0.7
  start_iteration: 100000
  stop_iteration: 500000
  block: [1, 32]

output:
  buckets: 256
  mu: 255

optimizer:
  learning_rate: 2.0e-4
  decay_rate: 0.1
  decay_iterations: [2000000, 2500000]
